language: node_js
node_js:
  - "8"

env:
  global:
    - secure: "EBUOWNuxoBJAJWnaaXoMcX55lBnz0LkMo/24webHjlMZaWtexK2yxtFixDE/j8zmCr0QQHSqQwAD4mOFo2CmBhoZUcC10dceQptluTWkaTfwNZHsERQbFSEvSuMYb1RpQYOq21z/hx3dk/ytcrIzPHFoEeG31pznNyBAHi+nbCS7ySJNmrl0EPlWU6mHQCNmDvZZFprkVdBZC0IZqTJQqtGgkwjDrcFxokbW0Cjm1D0+nX+5N0G9TZOUzggrskAALjX8FX+IyWSAp2oRwjiGqYT2PlMInOvecJ5xWg8g14PgSSViolRXz4zFZz+L4v5M14u5W7GafuadORea90RyKmA0fX4nfV7Yqsm6WJCZZk1PnSfbEOpzs/M5tMF3RemUE0uAPmH4xg0fcYipN6IHz0Yy/HK49tgMrYQaXyjpZ94VFlh5gkEaJEU/qMfV6mC1VzlO5ZfPL5n1pKhlxTV0Z+EOAv0tCB0mS4VQyPefopyzSYBUFlhfzEQd/ncRwqQtRlyBkZkDb16zymSOgBq28ShSeHHyofdmMWhdR3pVPXjW9M+XleBB5tpLQ/PF33ft19OpjOChmIwlvTBJrswHQcJTZFC/QLWw8AU7NHGbR57MQsRzf4uPaA6u1itv14ZmJhFPg7GzPUameb6z2by3GUt2ku20dwwSjeWoaWQzbes="

addons:
  ssh_known_hosts:
    - $DEPLOY_HOST

script:
  - npm run build

before_deploy:
  - openssl aes-256-cbc -K $encrypted_09958accfe56_key -iv $encrypted_09958accfe56_iv -in .travis/travis_deploy.enc -out .travis/travis_deploy -d
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/travis_deploy
  - ssh-add .travis/travis_deploy
  - ssh-keyscan -t $TRAVIS_SSH_KEY_TYPES -H $DEPLOY_HOST 2>&1 | tee -a $HOME/.ssh/known_hosts

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r -q $TRAVIS_BUILD_DIR/docs/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY
  on:
    branch: master
