language: node_js
node_js:
  - "8"

env:
  global:
    - secure: "EBUOWNuxoBJAJWnaaXoMcX55lBnz0LkMo/24webHjlMZaWtexK2yxtFixDE/j8zmCr0QQHSqQwAD4mOFo2CmBhoZUcC10dceQptluTWkaTfwNZHsERQbFSEvSuMYb1RpQYOq21z/hx3dk/ytcrIzPHFoEeG31pznNyBAHi+nbCS7ySJNmrl0EPlWU6mHQCNmDvZZFprkVdBZC0IZqTJQqtGgkwjDrcFxokbW0Cjm1D0+nX+5N0G9TZOUzggrskAALjX8FX+IyWSAp2oRwjiGqYT2PlMInOvecJ5xWg8g14PgSSViolRXz4zFZz+L4v5M14u5W7GafuadORea90RyKmA0fX4nfV7Yqsm6WJCZZk1PnSfbEOpzs/M5tMF3RemUE0uAPmH4xg0fcYipN6IHz0Yy/HK49tgMrYQaXyjpZ94VFlh5gkEaJEU/qMfV6mC1VzlO5ZfPL5n1pKhlxTV0Z+EOAv0tCB0mS4VQyPefopyzSYBUFlhfzEQd/ncRwqQtRlyBkZkDb16zymSOgBq28ShSeHHyofdmMWhdR3pVPXjW9M+XleBB5tpLQ/PF33ft19OpjOChmIwlvTBJrswHQcJTZFC/QLWw8AU7NHGbR57MQsRzf4uPaA6u1itv14ZmJhFPg7GzPUameb6z2by3GUt2ku20dwwSjeWoaWQzbes="
    - secure: "nydCMZigohxQFgXeJqziWwLpBBrZkH5H5pZEfFO9i/UQarjueapOx/Qdu2Cx6JUZkAdNS5zqgLbdrLW2RMR4lQoj8EDbdGkb1qfnrEL61VW1ksrH6qHvJoaOyanIbNpcanWvFELPOV3oeELp3i9SHjkAeg/qwF21wurCe1oJ3iByLskwp6Z9lvaSF63D7uw9HmH/rslKBVvSmWi6kmKwBQ4kgm0AqWttIG+4HryllaaLxMzqUpefcRzZqY0p+rSTtjHHLADxr6iPKozljJRSY58BcsstkK1QnwyvJUalHTWI+IsC0/602RINgO23FelzDQF/rvGBjw1/xSE5VyfOXQMIlNexBCRx+QC8FkFvIAGMARLohDbwVBK8hynMRYK1LAkeXRJIyuwGsZOpCIs7Sbp8okDAim0drhliaD+oPy0boL1JhuGgclX3ypLR7/RyN1T9USKud64qxBxj/Tmn+0iCQZ7nJw1gJizDxL8QtqN1iim3TWIcE0WGkwPP6MF7UuBU/hmxPxPaWaCCdt/NbwMPoTAdblm2XteeKBPAbU5A1fy1LaQHy0QYuXsapRkGxnoKBQRtkyaIobVnOryLFbtSqA/gxCelkP5v9fDSeFnL/Nk+N3I0qzoC8wLUZ8DW9Gd2GgYUYbLZKE86pZ3CJ8jUBDSaka+yaKkUdpx6Yyo="

addons:
  ssh_known_hosts:
    - $DEPLOY_HOST

script:
  - npm run build

before_deploy:
  - openssl aes-256-cbc -K $encrypted_09958accfe56_key -iv $encrypted_09958accfe56_iv -in .travis/travis_deploy.enc -out .travis/travis_deploy -d
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/travis_deploy
  - ssh-add .travis/travis_deploy
  - echo $KNOWN_HOST >> $HOME/.ssh/known_hosts

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r -q $TRAVIS_BUILD_DIR/docs/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY
  on:
    branch: master
