language: node_js
node_js:
  - "8"

env:
  global:
    - secure: "NzbwlNjJTg94K/Luc7jkxL5wi8bfz21Bdmt/uRFMuJ9BwMCBQeZYmbJTdcdeycDJdfK27wXUtPGIqJlwrXfDNk1bjYZjuw9/Zlmtf/1A1VzE6zfbtanU80MoUUS/Fh4utPUl+5MoGxmqrPoCw2iEar4kI7aMazppeYRPTMje88a0SACvU7v6Ow4VN5Fjqd+jSoFvZSiHqa2Fau1kbl6th83j7qO7KP29hboL9DNJ7c4knJ7GRwo4KzPfe+PyJCN4mWBKdn3k/NDn8caSO+lpmCFjilybot+Llx0D0kuzt0pghiLZvNfyPUX0khXZdK5cujmMOcSzFqfBxqK8csFAhREEYaECODJwymY1H0NECaKsFBEGaw0wQ/5UFQD/ZFAhmyvgb6xNclFdRnd8n8CuV1IO3FOtS03zgIzsnuLNLANux1TByzsXBo+MyDphslGsX8GsRP19tGHoLRUK7/doqEh2KeyVC5DKJpx5FWxXe8TKGkT/CMo7eE6FJhnfldBmxPvB1GNecn1IpBlYoJFhIVhE2w6Bdwp+QBtSORuaHSA5zBRRtf864pPDDMALvZk+OsPTCIEEv6JFBE+k+5RImcLTjZxfVV+RtriD3Vtth2T3HjdnD5a+mlFtojyUAfRbZXKcnE5JYFBkOqamDNLviN3pjNICVgJl+wY1FOHXCz8="

script:
  - npm run build

before_deploy:
  - openssl aes-256-cbc -K $encrypted_09958accfe56_key -iv $encrypted_09958accfe56_iv -in .travis/travis_deploy.enc -out .travis/travis_deploy -d
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/travis_deploy
  - ssh-add .travis/travis_deploy
  - ssh-keyscan -t $TRAVIS_SSH_KEY_TYPES -H $DEPLOY_HOST 2>&1 | tee -a $HOME/.ssh/known_hosts

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r -q $TRAVIS_BUILD_DIR/docs/ $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_DIRECTORY
  on:
    branch: master
