language: node_js
node_js:
- '8'
env:
  global:
    secure: "QOzsnJPbDmnrxf9Te4TtNlFckbJBVv/qvzb1L0k6DeBefSNNNBqEIYsRV8a1ExkuyuPBWh6JkNfbGX7XpN0s54AYJwr0JsJRjIQlTBYZGl2LLVnjlm2s/fcG84oat1jBh7wr3d/vzAESuSqN1BQw5U5cvd4zZCcHmkNsjYHICq1/nwt54UGv9HU7bGRu1nvhQK7D7FkVei+mBvNG7jlcFnzYxM89KDCqlGiE7jv2UIDESkAZtUMZmxDZ20Y0V5QUAEAKCLMsAUtcljrALbU2h5zELzfKMgCbqyqUBYrTm47kZKKtJGLFjF2geXBU+GzZ5E6f7mFtT5kz80P8Rmf7eOtyBVZxWne2eaM1MdYnlO5SvixXpzDfZqEA3dAH7WV7XNKqT5C9KJRnVCW8sYEF81cufnsYQZ9gXtO+I2l3MR7Dv2ix2IEFn5VC6sfnMZkJjvEsvKcl2DRRkgherAMNWroZJ4+kfi9WCCTTEzkDNhskZabRUYtD0a0BiZ4+9/rpxWdGNBH7Rn6ITQAp5Yx1U8HUPAtC+iCzfab1agus/3taX5ZazlngzusAoiLf9ItiaB3q0F1x8KF58j44YWGlxa7BFssz1Me1vLVaBNY6kSz7HRyZsgOmLD9xLlG3gDapTLGBUpRA9+OXwTj1PxCQQeJHnjK/FUrBjoR64jpjqrA="
script:
- npm run build
before_deploy:
- openssl aes-256-cbc -K $encrypted_09958accfe56_key -iv $encrypted_09958accfe56_iv
  -in .travis/travis_deploy.enc -out .travis/travis_deploy -d
- eval "$(ssh-agent -s)"
- chmod 600 .travis/travis_deploy
- ssh-add .travis/travis_deploy
- openssl aes-256-cbc -K $encrypted_09958accfe56_key -iv $encrypted_09958accfe56_iv
  -in .travis/known_hosts.enc -out .travis/known_hosts -d
- cat .travis/known_hosts >> $HOME/.ssh/known_hosts
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r -q $TRAVIS_BUILD_DIR/docs/ $DEPLOY_USER@$DEPLOY_HOST_IP:$DEPLOY_DIRECTORY
  on:
    branch: master
