language: node_js
node_js:
  - "8"

env:
  global:
    secure: "hxD9JwT++I56566aqkapNvlB0dc9u2T62BVHwx/jGY/YIyfHMpyaI4xsA73OkHlblWGyWAvc75vXAEBvakDKCtPj+a23r5Kdl7ocu2ztBr/gMIqzhNLU021yf7ztFhzcafmPpM24c30hSB4GX5F4cKKH/KGiTGlYyY9vvu7Li4B6cnNhjlbNeJ841Ptc4vTdBaMinjct4OxrS4ZWaHV+HxH4cjwVH+lU0Xq4TCZZiWVXBYWkN1m8jdrHEAOut9ZfTD8bRdv+f8zcxXPLUah8cysbVrU5LyW1j4p36eikmzhe3OHpfeLjGLZbH5KzRpPTxSK71qLFU5Xv8rbfDLW67FXDmf8MXXijlClNIykgt0AEjUpxQnCgf80e+Z+IxO5RepManBD+DTzlQzpYpuRT3K6owN0YQ+nsx/+q1xsQ3dW6WMUY4b8LZE7ldv+3tzWIMV79VvpFFed37cATHCiOKsKyAer7or8lpIz1mLdI80mLUF4mhhrOnSfPlNkaKQIUMJymPSGgsjo2esrND7Rt0zm/Wp0FBC50zWOmBiJadGxQjOmTNhymgMGb9JgXFlVcjjy7bIej9ywXhfdCS+xK8cfWjmPPnSThfnz6utCZfQMUN08DoCIfibZYFWoeV2A0NBW9klRmppZmMishSo2PiB13kaaKQET+ntFlFmuuWvY="

script:
  - npm run build

before_deploy:
  - openssl aes-256-cbc -K $encrypted_09958accfe56_key -iv $encrypted_09958accfe56_iv -in .travis/travis_deploy.enc -out .travis/travis_deploy -d
  - eval "$(ssh-agent -s)"
  - chmod 600 .travis/travis_deploy
  - ssh-add .travis/travis_deploy
  - ssh-keyscan -H $DEPLOY_HOST -t $TRAVIS_SSH_KEY_TYPES 2>&1 >> $HOME/.ssh/known_hosts
  - ssh-keyscan -H $DEPLOY_HOST_IP -t $TRAVIS_SSH_KEY_TYPES 2>&1 >> $HOME/.ssh/known_hosts
  - ssh-keyscan -H $DEPLOY_HOST,$DEPLOY_HOST_IP -t $TRAVIS_SSH_KEY_TYPES 2>&1 >> $HOME/.ssh/known_hosts

deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r -q $TRAVIS_BUILD_DIR/docs/ $DEPLOY_USER@$DEPLOY_HOST_IP:$DEPLOY_DIRECTORY
  on:
    branch: master
